=== pataphorce/lis652/joshsmusicschema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Joshsmusic">
	<xs:complexType>
        	<xs:sequence>
			<xs:element name="artist" type="xs:string"/>
			<xs:element name="albumtitle" type="xs:string"/>
			<xs:element name="genre" maxOccurs="unbounded">
				<xs:simpleType>
    					<xs:restriction base="xs:string">
      						<xs:enumeration value="Blues"/>
      						<xs:enumeration value="Comedy"/>
      						<xs:enumeration value="Country"/>
                      				<xs:enumeration value="Easy Listening"/>
      						<xs:enumeration value="Electronic"/>
      						<xs:enumeration value="Folk"/>
                      				<xs:enumeration value="Hip Hop"/>
      						<xs:enumeration value="Jazz"/>
      						<xs:enumeration value="Latin"/>
                      				<xs:enumeration value="Pop"/>
      						<xs:enumeration value="R&amp;B and Soul"/>
      						<xs:enumeration value="Rock"/>
                      				<xs:enumeration value="Other"/>
    					</xs:restriction>
  				</xs:simpleType>
			</xs:element>
			<xs:element name="releasedate" type="xs:date"/>
			<xs:element name="publisher" type="xs:string"/>
			<xs:element name="price" type="xs:decimal"/>
			<xs:element name="rating">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="tracklist" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="songtitle" type="xs:string" use="required"/>
					<xs:attribute name="length" type="xs:duration" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
    
</xs:schema>

=== pataphorce/lis652/GretaVanFleet.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- I couldn't download an xml editor so I hosted the schema file on a github account so I could reference it here -->
<Joshsmusic
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="https://pataphorce.github.io/lis652/joshsmusicschema.xsd">
  <artist>Greta Van Fleet</artist>
  <albumtitle>Anthem of the Peaceful Army</albumtitle>
  <genre>Blues</genre>
  <genre>Rock</genre>
  <releasedate>2018-10-19</releasedate>
  <publisher>Republic Records</publisher>
  <price>11.99</price>
  <rating>4</rating>
  <tracklist songtitle="Age of Man" length="PT6M06S"/>
  <tracklist songtitle="The Cold Wind" length="PT3M16S"/>
  <tracklist songtitle="When the Curtain Falls" length="PT3M42S"/>
  <tracklist songtitle="Watching Over" length="PT4M28S"/>
  <tracklist songtitle="Lover, Leaver (Taker, Believer)" length="PT6M01S"/>
  <tracklist songtitle="You're the One" length="PT4M25S"/>
  <tracklist songtitle="The New Day" length="PT2M44S"/>
  <tracklist songtitle="Mountain of the Sun" length="PT4M30S"/>
  <tracklist songtitle="Brave New World" length="PT5M00S"/>
  <tracklist songtitle="Anthem" length="PT4M41S"/>
</Joshsmusic>
